server:
  port: 9000

spring:
  profiles:
    active: dev
  datasource:
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    databaseName:
    serverName:
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate:
        cache.use_query_cache: false
        generate_statistics: false
        format_sql: true
